AWSTemplateFormatVersion: '2010-09-09'
Description: ACFS3 - Certificate creation

Parameters:
  DomainName:
    Type: String
  SubDomain:
    Type: String
  ApiDomain:
    Type: String
  CreateApex:
    Type: String
  HostedZoneId:
    Type: String

Conditions:
  CreateApexConfig: !Equals
    - !Ref CreateApex
    - 'yes'
  HasApiDomain: !Not
    - !Equals
      - !Ref ApiDomain
      - ''

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub '${SubDomain}.${DomainName}'
      SubjectAlternativeNames:
        Fn::If:
          - CreateApexConfig
          - !Ref DomainName
          - !Ref AWS::NoValue
        Fn::If:
          - HasApiDomain
          - !Ref ApiDomain
          - !Ref AWS::NoValue
      DomainValidationOptions:
        - DomainName: !Sub '${SubDomain}.${DomainName}'
          HostedZoneId: !Ref HostedZoneId
        - Fn::If:
            - CreateApexConfig
            - DomainName: !Ref DomainName
              HostedZoneId: !Ref HostedZoneId
            - !Ref AWS::NoValue
      ValidationMethod: DNS

Outputs:
  CertificateArn:
    Description: Issued certificate
    Value: !Ref Certificate
